"""GFSL-aligned Evolvo library."""

from .enums import (
    Category,
    ConfigProperty,
    DataType,
    Operation,
    CONTROL_FLOW_OPS,
    BOOLEAN_COMPARE_OPS,
    BOOLEAN_LOGIC_OPS,
    DECIMAL_OPS,
    LIST_QUERY_OPS,
    LIST_TARGET_OPS,
    LIST_VALUE_OPS,
    TENSOR_OPS,
    BINARY_OPS,
    UNARY_OPS,
)
from .slots import (
    ADDRESS_SLOT_COUNT,
    OP_SLOT_COUNT,
    DEFAULT_SLOT_COUNT,
    DEFAULT_PROBABILITY_BRANCHING,
    SLOT_TARGET_CAT,
    SLOT_TARGET_SPEC,
    SLOT_OPERATION,
    SLOT_SOURCE1_CAT,
    SLOT_SOURCE1_SPEC,
    SLOT_SOURCE2_CAT,
    SLOT_SOURCE2_SPEC,
    SLOT_NAMES,
    SLOT_NAME_TO_INDEX,
    SPEC_TYPE_SHIFT,
    SPEC_INDEX_MASK,
    pack_type_index,
    unpack_type_index,
    slot_name,
    resolve_slot_index,
)
from .custom_ops import (
    CustomOperation,
    CustomOperationManager,
    custom_operations,
    register_custom_operation,
    resolve_operation_name,
    infer_source_type,
)
from .values import ValueEnumerations
from .instruction import GFSLInstruction, SlotOption, describe_slot_option
from .weights import OperationWeights
from .validator import SlotValidator
from .builder import GFSLExpressionBuilder
from .genome import GFSLGenome, InstructionActivity
from .executor import GFSLExecutor, FunctionDefinition
from .evaluator import RealTimeEvaluator
from .model import RecursiveModelBuilder
from .evolver import GFSLEvolver
from .qlearning import GFSLQLearningGuide
from .supervised import (
    resolve_torch_accelerator,
    GFSLFeatureExtractor,
    GFSLSupervisedDirectionModel,
    GFSLSupervisedGuide,
)
from .kompute import (
    KomputeTypeSpec,
    KomputeTypeOverride,
    KomputeKernelBinding,
    KomputeBufferRef,
    KomputeKernelStage,
    KomputeUnsupportedInstruction,
    KomputeExecutionPlan,
    KomputeCompatibilityReport,
    KomputeInstructionRegistry,
    GFSLKomputePlanner,
    GFSLKomputeRuntime,
)
from .settings import (
    DEFAULT_COMPUTE_BACKEND,
    DEFAULT_KOMPUTE_RUNTIME_MODE,
    DEFAULT_KOMPUTE_WARN_ON_FALLBACK,
    DEFAULT_KOMPUTE_FAIL_HARD,
    DEFAULT_KOMPUTE_KEEP_VRAM_STATE,
    DEFAULT_KOMPUTE_MIN_NATIVE_STAGE_COUNT,
    DEFAULT_KOMPUTE_MIN_NATIVE_STAGE_SHARE,
    DEFAULT_KOMPUTE_MAX_UNSUPPORTED_SHARE,
    DEFAULT_KOMPUTE_MAX_UNSUPPORTED_COUNT,
    DEFAULT_KOMPUTE_FORCE_CPU_ON_PARTIAL_COVERAGE,
    DEFAULT_KOMPUTE_NATIVE_ENABLE_DECIMAL,
    DEFAULT_KOMPUTE_NATIVE_ENABLE_BOOLEAN_COMPARE,
    DEFAULT_KOMPUTE_NATIVE_ENABLE_BOOLEAN_LOGIC,
    DEFAULT_KOMPUTE_NATIVE_ENABLE_LIST_QUERY,
    DEFAULT_KOMPUTE_PLAN_CACHE_ENABLE,
    DEFAULT_KOMPUTE_PLAN_CACHE_MAX_ENTRIES,
    DEFAULT_KOMPUTE_PLAN_DISK_CACHE_ENABLE,
    DEFAULT_KOMPUTE_PLAN_DISK_CACHE_DIR,
    DEFAULT_KOMPUTE_PLAN_DISK_CACHE_MAX_FILES,
)
from .demos import example_formula_discovery, example_neural_architecture_search

__all__ = [
    "Category",
    "ConfigProperty",
    "DataType",
    "Operation",
    "CONTROL_FLOW_OPS",
    "BOOLEAN_COMPARE_OPS",
    "BOOLEAN_LOGIC_OPS",
    "DECIMAL_OPS",
    "LIST_TARGET_OPS",
    "LIST_VALUE_OPS",
    "LIST_QUERY_OPS",
    "TENSOR_OPS",
    "BINARY_OPS",
    "UNARY_OPS",
    "ADDRESS_SLOT_COUNT",
    "OP_SLOT_COUNT",
    "DEFAULT_SLOT_COUNT",
    "DEFAULT_PROBABILITY_BRANCHING",
    "SLOT_TARGET_CAT",
    "SLOT_TARGET_SPEC",
    "SLOT_OPERATION",
    "SLOT_SOURCE1_CAT",
    "SLOT_SOURCE1_SPEC",
    "SLOT_SOURCE2_CAT",
    "SLOT_SOURCE2_SPEC",
    "SLOT_NAMES",
    "SLOT_NAME_TO_INDEX",
    "SPEC_TYPE_SHIFT",
    "SPEC_INDEX_MASK",
    "pack_type_index",
    "unpack_type_index",
    "slot_name",
    "resolve_slot_index",
    "CustomOperation",
    "CustomOperationManager",
    "custom_operations",
    "register_custom_operation",
    "resolve_operation_name",
    "infer_source_type",
    "ValueEnumerations",
    "OperationWeights",
    "GFSLInstruction",
    "SlotOption",
    "describe_slot_option",
    "SlotValidator",
    "GFSLExpressionBuilder",
    "InstructionActivity",
    "GFSLGenome",
    "FunctionDefinition",
    "GFSLExecutor",
    "RealTimeEvaluator",
    "RecursiveModelBuilder",
    "GFSLEvolver",
    "GFSLQLearningGuide",
    "resolve_torch_accelerator",
    "GFSLFeatureExtractor",
    "GFSLSupervisedDirectionModel",
    "GFSLSupervisedGuide",
    "KomputeTypeSpec",
    "KomputeTypeOverride",
    "KomputeKernelBinding",
    "KomputeBufferRef",
    "KomputeKernelStage",
    "KomputeUnsupportedInstruction",
    "KomputeExecutionPlan",
    "KomputeCompatibilityReport",
    "KomputeInstructionRegistry",
    "GFSLKomputePlanner",
    "GFSLKomputeRuntime",
    "DEFAULT_COMPUTE_BACKEND",
    "DEFAULT_KOMPUTE_RUNTIME_MODE",
    "DEFAULT_KOMPUTE_WARN_ON_FALLBACK",
    "DEFAULT_KOMPUTE_FAIL_HARD",
    "DEFAULT_KOMPUTE_KEEP_VRAM_STATE",
    "DEFAULT_KOMPUTE_MIN_NATIVE_STAGE_COUNT",
    "DEFAULT_KOMPUTE_MIN_NATIVE_STAGE_SHARE",
    "DEFAULT_KOMPUTE_MAX_UNSUPPORTED_SHARE",
    "DEFAULT_KOMPUTE_MAX_UNSUPPORTED_COUNT",
    "DEFAULT_KOMPUTE_FORCE_CPU_ON_PARTIAL_COVERAGE",
    "DEFAULT_KOMPUTE_NATIVE_ENABLE_DECIMAL",
    "DEFAULT_KOMPUTE_NATIVE_ENABLE_BOOLEAN_COMPARE",
    "DEFAULT_KOMPUTE_NATIVE_ENABLE_BOOLEAN_LOGIC",
    "DEFAULT_KOMPUTE_NATIVE_ENABLE_LIST_QUERY",
    "DEFAULT_KOMPUTE_PLAN_CACHE_ENABLE",
    "DEFAULT_KOMPUTE_PLAN_CACHE_MAX_ENTRIES",
    "DEFAULT_KOMPUTE_PLAN_DISK_CACHE_ENABLE",
    "DEFAULT_KOMPUTE_PLAN_DISK_CACHE_DIR",
    "DEFAULT_KOMPUTE_PLAN_DISK_CACHE_MAX_FILES",
    "example_formula_discovery",
    "example_neural_architecture_search",
]
